package config

/**
 * 서버별로 생성할 Job 정보
 */
return [
        'demo'       : ['api', 'wms', 'admin', 'socket', 'oauth'],
        'demo2'      : ['api', 'wms', 'admin', 'socket', 'oauth'],
        'demo3'      : ['api', 'wms', 'admin', 'socket', 'oauth'],
        'demo4'      : ['api', 'wms', 'admin', 'socket', 'oauth'],
        'dev-so-pm'  : ['api', 'wms', 'admin', 'socket', 'oauth', 'so_pm'],
        'dev-01'     : ['api', 'wms', 'admin', 'socket', 'oauth', 'api_v3', 'socket_v3', 'admin_v3', 'wms_v3', 'etag'],
        'dev-02'     : ['api', 'wms', 'admin', 'socket', 'oauth'],
        'dev-04'     : ['api', 'wms', 'admin', 'socket', 'oauth'],
        'dev-05'     : ['api', 'wms', 'admin', 'socket', 'oauth'],
        'dev-06'     : ['api', 'wms', 'admin', 'socket', 'oauth'],
        'dev-07'     : ['api', 'wms', 'admin', 'socket', 'oauth'],
        'dev-08'     : ['api', 'wms', 'admin', 'socket', 'oauth'],
        'dev-09'     : ['api', 'wms', 'admin', 'socket', 'oauth'],
        'dev-10'     : ['api', 'wms', 'admin', 'socket', 'oauth'],
        'dev-11'     : ['api', 'wms', 'admin', 'socket', 'oauth'],
        'dev-12'     : ['api', 'wms', 'admin', 'socket', 'oauth'],
        'dev-13'     : ['api', 'wms', 'admin', 'socket', 'oauth'],
        'dev-14'     : ['api', 'wms', 'admin', 'socket', 'oauth'],
        'dev-15'     : ['api', 'wms', 'admin', 'socket', 'oauth'],
        'dev-16'     : ['api', 'wms', 'admin', 'socket', 'oauth'],
        'dev-17'     : ['api', 'wms', 'admin', 'socket', 'oauth'],
        'dev-18'     : ['api', 'wms', 'admin', 'socket', 'oauth'],
        'dev-19'     : ['api', 'wms', 'admin', 'socket', 'oauth'],
        'dev-20'     : ['api', 'wms', 'admin', 'socket', 'oauth'],
        'dev-21'     : ['api', 'wms', 'admin', 'socket', 'oauth'],
        'dev-22'     : ['api', 'wms', 'admin', 'socket', 'oauth'],
        'dev-23'     : ['api', 'wms', 'admin', 'socket', 'oauth'],
        'dev-24'     : ['api', 'wms', 'admin', 'socket', 'oauth'],
        'dev-25'     : ['api', 'wms', 'admin', 'socket', 'oauth'],
        'dev-semi-rpa': ['api', 'wms', 'admin'],
        'anam-rtls'  : ['api', 'oauth', 'rtls', 'socket', 'admin', 'wms'],
        'aisa1'      : ['wms', 'rtls', 'socket', 'api'],
        'dev-mfhs'   : ['wms', 'rtls', 'socket', 'api', 'admin'],
        'dev-roadpavement' : ['api', 'rtls', 'socket', 'admin', 'wms'],
        'stage-01' : ['api', 'wms', 'admin', 'socket', 'oauth'],
]
